[[redirects]]
  from = "https://xuannwang.netlify.com/*"
  to = "https://xuann.wang/:splat"
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
